#批量添加和修改、删除front matter配置文件

# 需要批量处理的路径，docs文件夹内的文件夹  (数组，映射路径：path[0]/path[1]/path[2] ... )
path:
  - docs # 第一个成员必须是docs,下面注释的智能单个不注释来修改
  - 00.目录页
  # - 01.前端
  # - 02.后端
  # - 03.人工智能
  # - 04.更多
  # - 05.关于
  # - 06.收藏夹
  # - 07.页面
  # - 08.技术

# 要删除的字段 (数组)
delete:
  # - tags

 # 要添加、修改front matter的数据 （front matter中没有的数据则添加，已有的数据则覆盖）
data:
  author:
    name: carolin-violet
    link: https://github.com/carolin-violet
